version: "3"

services:
  bambyte:
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
      args:
        - DISCORD_TOKEN=${SECRET_DISCORD_TOKEN}
        - GIPHY_TOKEN=${SECRET_GIPHY_TOKEN}